name: Workflow For Regular Java Library
descriptiion: |
  This workflow is used to build, test, and deploy a regular Java library to JFrog Artifactory.
  It also performs static code analysis using SonarQube and dependency check.

on: 
  workflow_dispatch:
permissions: write-all
jobs:
  upload:

    uses: diego4bits/reusable-workflow-components/.github/workflows/regular-java-lib-workflow.yml@main
    with:
      java-distribution: ${{ vars.JAVA_DISTRIBUTION }}
      java-version: ${{ vars.JAVA_VERSION }}
      jf-url: ${{ vars.JF_URL }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      sonar-project-name: ${{ vars.SONAR_PROJECT_NAME }}
    secrets:
      jf-access-token: ${{ secrets.JF_ACCESS_TOKEN }}
      sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      sonar-organization: ${{ secrets.SONAR_ORGANIZATION }}
      # These attrinutes will be needed to resolve dependencies from JFrog Artifactory.
      # jf-server-id-resolve: ${{ vars.JF_SERVER_ID_RESOLVE }}
      # jf-repo-resolve-releases: ${{ vars.JF_REPO_RESOLVE_RELEASES }}
      # jf-repo-resolve-snapshots: ${{ vars.JF_REPO_RESOLVE_SNAPSHOTS }}