name: Test JFrog Maven Deploy (CLI-only)

on: 
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   
      contents: read


    steps:
      - name: Set up JFrog CLI
        uses: diego4bits/reusable-workflow-components/.github/workflows/regular-java-lib-workflow.yml@main
        with:
          java-distribution: ${{ vars.JAVA_DISTRIBUTION }}
          java-version: ${{ vars.JAVA_VERSION }}
          jf-url: ${{ vars.JF_URL }}
          jf-access-token: ${{ secrets.JF_ACCESS_TOKEN }}
          jf-server-id-resolve: ${{ vars.JF_SERVER_ID_RESOLVE }}
          jf-repo-resolve-releases: ${{ vars.JF_REPO_RESOLVE_RELEASES }}
          jf-repo-resolve-snapshots: ${{ vars.JF_REPO_RESOLVE_SNAPSHOTS }}
