name: Workflow For Tagged Version
description: |
  This workflow is used to build, test, and deploy a tagged version of a Java library to JFrog Artifactory.
  It is triggered by the semantic release with bot a push event of the with a tag that matches the pattern '*.*.*'.
# minor patch 2
on: 
  push:
    tags:
      - '*.*.*'
permissions: write-all
jobs:
  upload:

    uses: diego4bits/reusable-workflow-components/.github/workflows/tagged-version-workflow.yml@main
    with:
      java-distribution: ${{ vars.JAVA_DISTRIBUTION }}
      java-version: ${{ vars.JAVA_VERSION }}
      jf-url: ${{ vars.JF_URL }}
      jf-upload-repo-path: ${{ vars.JF_UPLOAD_REPO_PATH }}
    secrets:
      jf-access-token: ${{ secrets.JF_ACCESS_TOKEN }}
      # These attrinutes will be needed to resolve dependencies from JFrog Artifactory.
      # jf-server-id-resolve: ${{ vars.JF_SERVER_ID_RESOLVE }} " This is optional"
      # jf-repo-resolve-releases: ${{ vars.JF_REPO_RESOLVE_RELEASES }}
      # jf-repo-resolve-snapshots: ${{ vars.JF_REPO_RESOLVE_SNAPSHOTS }}